version: '3.8'

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tournament
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./tournament-backend
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgres://admin:password@db:5432/tournament
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - db
    volumes:
      - ./tournament-backend:/app

  frontend:
    build: ./my-signup-form
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
