# Generated by Django 6.0.2 on 2026-02-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('belt_rank', models.CharField(choices=[('white', 'White Belt'), ('yellow', 'Yellow Belt'), ('green', 'Green Belt'), ('blue', 'Blue Belt'), ('red', 'Red Belt'), ('black', 'Black Belt'), ('black-dan2', 'Black Belt (2nd Dan)'), ('black-dan3', 'Black Belt (3rd Dan)')], max_length=20)),
                ('weight', models.IntegerField()),
                ('school_name', models.CharField(max_length=200)),
                ('poomsae', models.BooleanField(default=False)),
                ('board_breaking', models.BooleanField(default=False)),
                ('sparring', models.BooleanField(default=False)),
                ('agreed_to_waiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
